# The URL the site will be built for
base_url = "https://mygo.vantao.cn"

title = "PhotoLics"

description = "Website of Junying Li's Research Group."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
smart_punctuation = true

[markdown.highlighting]
theme = "github-dark"

[extra]
num_recent_posts = 3
author = "Junying Li's Research Group"
email = ""
source = "https://github.com/HIAS-MyGO"
